# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: fc0905112f479297edabfaf174031474b17ff9451bcadda7121f5cc3d9cde41987879382918c009e218b65be39f39bdf068fad16134fa50b12390a0bea7727d1

test:
  secret_key_base: a54ef6fe211f0ce04a455b37394a25147710ec07a6ae10231878aae2eb70a22dec92e534b8e1dcfc1044aa32a154f7c9af53e182446975741f60cd036218ee2e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
